version: '3.8'

services:
  mysql:
    container_name: remote_jobs_mysql
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: remote_jobs
